In [1]:
import os
os.chdir("../")
%pwd

'd:\\BookWise-AI-Book-Recommender'

In [2]:
import pandas as pd
import numpy as np

C:\Users\Deependra Verma\AppData\Local\Temp\ipykernel_30808\2162656668.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
books = pd.read_csv("Data\\Books.csv")
users = pd.read_csv("Data\\Users.csv")
ratings = pd.read_csv("Data\\Ratings.csv")

C:\Users\Deependra Verma\AppData\Local\Temp\ipykernel_30808\2278059703.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Data\\Books.csv")

In [4]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [6]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [7]:
books.shape, users.shape, ratings.shape

((271360, 8), (278858, 3), (1149780, 3))

In [8]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [9]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [10]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [11]:
books.duplicated().sum()

0

In [12]:
users.duplicated().sum()

0

In [13]:
ratings.duplicated().sum()

0

# Popularity Based Recommeder System

In [14]:
ratings_with_book_name = books.merge(ratings, on = "ISBN")

In [15]:
ratings_with_book_name

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400,0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385,0
...,...,...,...,...,...,...,...,...,...,...
1031131,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,276463,7
1031132,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,276579,4
1031133,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,276680,0
1031134,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,276680,0
1031135,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,276680,0

In [16]:
ratings_with_book_name.shape

(1031136, 10)

In [17]:
ratings_with_book_name.sample(5)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
483112,0884861236,Jo Petty's Words to Live by: A Treasury of Fav...,Jo Petty,1995,Bristol Park Books,http://images.amazon.com/images/P/0884861236.0...,http://images.amazon.com/images/P/0884861236.0...,http://images.amazon.com/images/P/0884861236.0...,123095,6
128827,0440221471,The Runaway Jury,JOHN GRISHAM,1997,Dell,http://images.amazon.com/images/P/0440221471.0...,http://images.amazon.com/images/P/0440221471.0...,http://images.amazon.com/images/P/0440221471.0...,213350,0
448041,1573240389,Wild Words from Wild Women: An Unbridled Colle...,Autumn Stephens,1996,Conari Press,http://images.amazon.com/images/P/1573240389.0...,http://images.amazon.com/images/P/1573240389.0...,http://images.amazon.com/images/P/1573240389.0...,108155,0
389442,0440473519,Ramona the Brave (Ramona Quimby (Paperback)),Beverly Cleary,1984,Bantam Doubleday Dell,http://images.amazon.com/images/P/0440473519.0...,http://images.amazon.com/images/P/0440473519.0...,http://images.amazon.com/images/P/0440473519.0...,219546,9
371519,0380818973,Asking for Trouble: A Novel,Elizabeth Young,2001,Avon Trade,http://images.amazon.com/images/P/0380818973.0...,http://images.amazon.com/images/P/0380818973.0...,http://images.amazon.com/images/P/0380818973.0...,40914,7

In [48]:
num_of_ratings = ratings_with_book_name.groupby("Book-Title")["Book-Rating"].count().reset_index()
num_of_ratings.rename(columns={"Book-Rating":"num of ratings"},inplace=True)

In [49]:
num_of_ratings

                                               Book-Title  num of ratings
0        A Light in the Storm: The Civil War Diary of ...               4
1                                   Always Have Popsicles               1
2                    Apple Magic (The Collector's series)               1
3        Ask Lily (Young Women of Faith: Lily Series, ...               1
4        Beyond IBM: Leadership Marketing and Finance ...               1
...                                                   ...             ...
241066                                      Ã?Â?lpiraten.               2
241067                     Ã?Â?rger mit Produkt X. Roman.               4
241068                                Ã?Â?sterlich leben.               1
241069                              Ã?Â?stlich der Berge.               3
241070                                  Ã?Â?thique en toc               2

[241071 rows x 2 columns]

In [53]:
avg_book_rating = ratings_with_book_name.groupby("Book-Title")["Book-Rating"].mean().reset_index()
avg_book_rating.rename(columns={"Book-Rating":"Avg Rating"}, inplace=True)

In [54]:
avg_book_rating

                                               Book-Title  Avg Rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [56]:
popularity_df = num_of_ratings.merge(avg_book_rating,on="Book-Title")

In [57]:
popularity_df

,Book-Title,num of ratings,Avg Rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [74]:
final_popular = popularity_df[(popularity_df["num of ratings"]>=250) & (popularity_df["Avg Rating"]>2)].sort_values("Avg Rating",ascending=False).head(50)

In [75]:
final_popular

,Book-Title,num of ratings,Avg Rating
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [89]:
popular_df = final_popular.merge(books,on="Book-Title")[["Book-Title","num of ratings","Avg Rating","Book-Author","Image-URL-M"]].drop_duplicates("Book-Title")

In [91]:
popular_df.shape

(50, 5)

In [92]:
popular_df

,Book-Title,num of ratings,Avg Rating,Book-Author,Image-URL-M
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,510,4.700000,Harper Lee,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,898,4.642539,Dan Brown,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,430,4.551163,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,449,4.545657,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,1295,4.468726,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...
63,1984,284,4.454225,George Orwell,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,253,4.450593,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,265,4.449057,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,774,4.447028,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,Michael Moore,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),723,4.334716,Anita Diamant,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,268,4.328358,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,252,4.273810,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,409,4.264059,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,526,4.218631,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,283,4.173145,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,Billie Letts,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,275,4.098182,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,664,4.088855,Yann Martel,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,389,4.087404,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",265,4.086792,Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,279,4.075269,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,490,4.055102,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,302,4.006623,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,322,4.006211,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,314,3.964968,Alice Walker,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,256,3.960938,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,262,3.900763,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),278,3.888489,Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,266,3.875940,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,457,3.820569,James Patterson,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,259,3.818533,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,413,3.796610,John Irving,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,ANNE RICE,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),356,3.772472,Janet Fitch,http://images.amazon.com/images/P/0316284955.0...

# Collaborative Filtering Based recommender System

In [93]:
ratings_with_book_name

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,User-ID,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,2,0
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,8,5
2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11400,0
3,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,11676,8
4,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,41385,0
...,...,...,...,...,...,...,...,...,...,...
1031131,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,276463,7
1031132,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,276579,4
1031133,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,276680,0
1031134,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,276680,0
1031135,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,276680,0

In [113]:
ratings_with_book_name.groupby("User-ID")["Book-Title"].count()>200

User-ID
2         False
8         False
9         False
10        False
12        False
          ...
278846    False
278849    False
278851    False
278852    False
278854    False
Name: Book-Title, Length: 92106, dtype: bool

In [108]:
ratings_with_book_name["User-ID"].isin(user_greater_than_200)

0          False
1          False
2          False
3           True
4          False
           ...
1031131    False
1031132    False
1031133    False
1031134    False
1031135    False
Name: User-ID, Length: 1031136, dtype: bool